### ISSUE TITLE
讲下编辑怎么实现的？

### ISSUE THREAD

**Issue by sumic** [myloveGy/yii2-ace-admin#16]

**Comment by myloveGy** [comment]
1、搜索POST参数70多个，因为jquery.datatables 默认就会携带很多参数, 我只会把表单搜索参数追加到默认参数里面，表单查询参数后台接收Yii::$app->request->post('params'); 具体处理可以看 common\strategy\DataTables 类的 getRequest() 方法，其他的POST参数是jquery.datatables 默认就会携带的；如果你觉得多的话，你可以反过来，把你需要的jquery.datatabls默认参数有用的(比如分页参数，请求次数参数) 追加到表单查询参数中去，然后提交到后台处理
2、编辑怎么实现的？前端还是后端，前端的话，因为jquery.datatables 会把每一行的数据保存在下来，通过datatables.data()获取到所有数据，返回一个数组，通过索引获取到指定哪行的数据，重新赋值到表单上面就好了

**Comment by sumic** [comment]
恩，感谢。已经看到处理方式了，你根据datatables的默认参数来取排序，还是很不错的。学习了，代码很不错。感谢分享。

**Comment by sumic** [comment]
不过我发现了你改的mtables的兼容性不是很好。IE8下面就没法用。其他的暂时不知道，我这里测试机是win7的。ace模版默认的显示都没有问题的。

**Comment by myloveGy** [comment]
嗯嗯！我没有测试过兼容性呢！
