### ISSUE TITLE
isHide属性在详情页面不起作用。

### ISSUE THREAD

**Issue by sumic** [myloveGy/yii2-ace-admin#17]
isHide属性在表格列表页面正常，在详情页面还是显示出来了。

**Comment by sumic** [comment]
"bViews":false,
加了个这个属性解决了，不知道有没有其他的影响。

**Comment by myloveGy** [comment]
bViews 就是详情是否显示，isHide 表示表格列是否隐藏， isExport 设置了就是不导出该列数据

**Comment by sumic** [comment]
恩，看文档没看到。看代码发现的：）
