### ISSUE TITLE
发现一个权限管理的前端BUG

### ISSUE THREAD

**Issue by sumic** [myloveGy/yii2-ace-admin#19]
当导航栏目大于两级的时候，在分配权限页面，左侧导航栏点击根菜单会报错。
`edit?name=admin:1788 Uncaught TypeError: Cannot read property 'split' of null
    at HTMLDivElement.<anonymous> (edit?name=admin:1788)
    at HTMLDivElement.dispatch (jquery.min.js:3)
    at HTMLDivElement.r.handle (jquery.min.js:3)
    at Object.trigger (jquery.min.js:3)
    at n.fn.init.triggerHandler (jquery.min.js:3)
    at a.jstree.plugins.checkbox.trigger (jstree.min.js:2)
    at a.jstree.plugins.checkbox.select_node (jstree.min.js:3)
    at a.jstree.plugins.checkbox.activate_node (jstree.min.js:3)
    at a.jstree.plugins.checkbox.activate_node (jstree.min.js:4)
    at a.jstree.plugins.checkbox.<anonymous> (jstree.min.js:2)`

原因分析：当大于两级的时候，父菜单没有地址（URL）,所以选择的时候会在NULL上调用了split方法。
修改：
` $(function(){
        $("#tree-one").jstree({
            "plugins" : ["checkbox" ],
            core: {
                "animation" : 0,
                "check_callback" : true,
                 data: <?=Json::encode($trees)?>
            }
        }).on('changed.jstree', function(e, data){
            if (data.action === "select_node" || data.action === "deselect_node") {
                var isChecked = data.action === "select_node",
                    // 选中的是目录
                    length = data.node.children.length,
                    attributes = [];
                if (length > 0) {
                    for (var i = 0; i < length; i ++) {
                          //增加了为空的判断，问题解决
                        if(data.instance.get_node(data.node.children[i]).data != null){
                        	 attributes.push(data.instance.get_node(data.node.children[i]).data.split("/")[0]);
                           }
                    }
                } else {
                    attributes.push(data.node.data.split("/")[0]);
                }

                attributes.forEach(function(attribute) {
                    $("input[value^='" + attribute + "/']").prop('checked', isChecked);
                });
            }
        });`

**Comment by myloveGy** [comment]
bug 已经修复、你那样修改没有报错了，但是功能没有实现；修改内容如下：
```
// 添加函数、获取选择、或者取消选择的节点属性
function getChildrenAttributes(data, parent_object) {
        var array_attributes = [], length = data.children.length;
        if (length > 0) {
            for (var i = 0; i < length; i++) {
                var tmp_data = parent_object.instance.get_node(data.children[i]);
                array_attributes.push.apply(array_attributes, getChildrenAttributes(tmp_data, parent_object));
            }
        } else if (data.data != null) {
            array_attributes.push(data.data.split("/")[0]);
        }

        return array_attributes;
    }

// js tree 的 changed.jstree 事件中，attributes 使用 getChildrenAttributes() 获取
$("#tree-one").jstree({
            "plugins": ["checkbox"],
            core: {
                "animation": 0,
                "check_callback": true,
                data: <?=Json::encode($trees)?>
            }
        }).on("changed.jstree", function (e, data) {
            if (data.action === "select_node" || data.action === "deselect_node") {
                var isChecked = data.action === "select_node",
                    attributes = getChildrenAttributes(data.node, data);
                attributes.forEach(function (attribute) {
                    $("input[value^='" + attribute + "/']").prop("checked", isChecked);
                });
            }
        });
```

**Comment by sumic** [comment]
后来我又改了下，修复了就好。
