### ISSUE TITLE
关于异步上传的建议

### ISSUE THREAD

**Issue by sumic** [myloveGy/yii2-ace-admin#21]
现在上传为异步上传方式，假如上传了文件，不点击确定就会出现文件已经上传了，但是却没有入库。可以改成提交后上传更符合逻辑一点。

**Comment by myloveGy** [comment]
文件通过异步方式上传，操作比较方便，对于用户的体验度也要好一点。确实存在你说的，存在文件浪费情况！但现在的大型应用，很少把文件直接保存在自己的服务器上面， 所以这点可以忽悠！如果你不喜欢这种方式，可以自己实现文件上传的方式！
