### ISSUE TITLE
Language English or indonesia translate

### ISSUE THREAD

**Issue by putrapuices** [myloveGy/yii2-ace-admin#25]
Hi..i want to translate admin dashboard yii2-ace-admin to english or indonesian Language...please help me

**Comment by myloveGy** [comment]
You only need to modify the corresponding language in the configuration file, and then add the translation file for the corresponding language

Modify the corresponding language in the configuration file on the homepage
main.php 
```php
return [
    'language' => 'en-US',
]
```

Then add the translation file for the corresponding language
main.php
```php
return [
'components' => [
'i18n' => [
            'translations' => [
                'admin' => [
                    'class'          => 'yii\i18n\PhpMessageSource',
                    'sourceLanguage' => 'en-Us',
                    'basePath'       => '@jinxing/admin/messages',
                ],
            ],
        ],
],
];
```
The translation file path needs to be changed to your path, corresponding to Chinese files for your language translation
My Chinese translation file is at：`vender/jinxing/yii2-admin/src/message` Under contents

The current multi-language support is not very good, I will inherit the update
