### ISSUE TITLE
用你的命令安装不了，自己下载了vendor放进去，一直报错

### ISSUE THREAD

**Issue by justpaybank** [myloveGy/yii2-ace-admin#6]
php composer.phar create-project liujx/yii2-app-advanced  
这个命令一直报错，说库找不到
c:\composer>php composer.phar create-project liujx/yii2-app-advanced
Installing liujx/yii2-app-advanced (1.2.2)
  - Installing liujx/yii2-app-advanced (1.2.2): Loading from cache
Created project in C:\composer\yii2-app-advanced
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2 2.0.9 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.8 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.7 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.6 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.13.1 requires bower-asset/jquery 3.2.*@stable | 3.

我有用vpn连接还是这个结果。

我就下载你的源代码，然后yii2的vendor目录放进去，打开后台页面好像有库找不到，也是报错

**Comment by justpaybank** [comment]
我在本地打开后台
http://127.0.0.1/aceadmin/backend/web/
结果这样：
Invalid Parameter – yii\base\InvalidParamException
The file or directory to be published does not exist: C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\aceadmin/vendor\bower/bootstrap/dist

1. in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\aceadmin\vendor\yiisoft\yii2\web\AssetManager.php at line 456
447448449450451452453454455456457458459460461462463464465    public function publish($path, $options = [])
    {
        $path = Yii::getAlias($path);
 
        if (isset($this->_published[$path])) {
            return $this->_published[$path];
        }
 
        if (!is_string($path) || ($src = realpath($path)) === false) {
            throw new InvalidParamException("The file or directory to be published does not exist: $path");
        }
 
        if (is_file($src)) {
            return $this->_published[$path] = $this->publishFile($src);
        }
 
        return $this->_published[$path] = $this->publishDirectory($src, $options);
    }
 
2. in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\aceadmin\vendor\yiisoft

**Comment by myloveGy** [comment]
你的问题都是一个问题导致的！你的 composer 没有安装 [Composer Asset插件:](https://github.com/fxpio/composer-asset-plugin)
```
php composer.phar global require "fxp/composer-asset-plugin:^1.2.0"
```
需要先安装，然后再重新在安装

**Comment by justpaybank** [comment]
按照你说的，下载成功了，但是我初始化之后，运行根目录下的index.php来创建数据库，总是显示 服务器繁忙，请稍后再试。  我就手工创建了数据库并导入了根目录下的yii2.sql，然后自己将backend下的配置文件改为：
$config = [
    'components' => [
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'cookieValidationKey' => 'v8a4_ajRC84J2KMfky86KHNYwmZ5rOiw',
        ],
		
		'db' => [
		'class' => 'yii\db\Connection',
		'dsn' => 'mysql:host=localhost;dbname=aceadmin',
		'username' => 'root',
		'password' => '',
		'charset' => 'utf8',
		],
		
    ],
];

之后再运行这个后台 http://127.0.0.1/aceadmin/backend/web/ ,  页面出现了，但是显示非常不正常，大部分内容都显示不出来呀

**Comment by justpaybank** [comment]
![image](https://user-images.githubusercontent.com/4658033/35675338-9fbb98de-0782-11e8-9957-26130a0c936b.png)

这是我打开页面的样子，哪里出问题了呀

**Comment by myloveGy** [comment]
你只要为项目单独设置一个虚拟目录就好了，目录路径到backend/web下面。你现在是资源加载有问题！

**Comment by justpaybank** [comment]
十分感谢，已经没有问题了。请问我是否自己能改成不从根目录下加载资源呀？因为我想将这个admin放在网站的子目录下面。

**Comment by myloveGy** [comment]
你把视图里面的views/site/index.php 里面的资源加载路径改下就好了

**Comment by kingduyuan** [comment]
关于这个和TP的后台 还有些问题想请教 能否告知一下QQ呢

**Comment by myloveGy** [comment]
QQ: 821901008
