### ISSUE TITLE
安装了TP和YII的后台现在都是样式问题 

### ISSUE THREAD

**Issue by kingduyuan** [myloveGy/yii2-ace-admin#7]
![qq 20180203154834](https://user-images.githubusercontent.com/28615043/35765225-aa1fa1e8-08fa-11e8-9892-f6730f5fb549.png)
![qq 20180203155017](https://user-images.githubusercontent.com/28615043/35765226-aa5608e6-08fa-11e8-8e67-294cda78c8c6.png)
![qq 20180203155448](https://user-images.githubusercontent.com/28615043/35765227-aa8dae18-08fa-11e8-8379-735ba08f3104.png)
哪里的配置有问题吗？只是在你的基础上改了下 数据库配置 其他的没动

**Comment by myloveGy** [comment]
都是一样的，你需要单独配置域名的

**Comment by kingduyuan** [comment]
@myloveGy 我试一下  大神有qq吗 或者群

**Comment by myloveGy** [comment]
我的QQ: 821901008

**Comment by wooliaolin** [comment]
697549103 加群 交流
